export const mentorImages = [
  { 
    src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/kane_mentor-uHOTyUTUHqetRIYKCWKDNwALX0aEzo.png", 
    alt: "Kane", 
    className: "bg-white object-cover object-[center_65%]" 
  },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ttrades-DHBbQvHZVjhdz641Mtc4PRMzTYfa32.png", alt: "TTrades" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/umar-ZU5aOhaO6GPLvAWCuifQPTBCw6TmJ3.png", alt: "Umar" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mooretrades-TRIiQYwQT23qW5vJSXxZQwcMFabstY.png", alt: "Moore Trades", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tjr-eh55QyZEUd3vDG9DvO9Sve5kqeMLOI.png", alt: "TJR" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/tori-hrybXGIGZ82QsJPX9CmVjaPxCLgFkT.png", alt: "Tori" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/f4xliving-0K77iCkjCFlAPwJcAZjzG2Xej6na26.jpg", alt: "F4X Living" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/ict-G7MSpuZJvBJUnLPJnBtlCWlOa7ze1U.jpg", alt: "ICT" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Wieland_patrick-OYcWxU9WxP07JjlXSbinLNBqb2KcKC.png", alt: "Patrick Wieland", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/mason-jIwynCjnqL1SwQkq5BWvVHJ5fd5ILT.png", alt: "Mason", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/justin-Ht6ws8nyQWCu2atIGbCu3l7MtEQRC3.png", alt: "Justin", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/dante-7fRyWGwWF2KHnNAFk0JgsEyKVmPOU3.png", alt: "Dante", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/OCs7W2zb_400x400-bq2QP7lWCARbzDBxtuhnXioNZlmlJ1.jpg", alt: "TraderTom" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/WAdsNqKg_400x400-73F3D5zqDyjcY0bNYkh04HV9wTgbr1.jpg", alt: "Abstract Logo" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/YYWaGyNp_400x400-removebg-preview-XC7hf7L0JffVPQbbhrX8u4j91qsin8.png", alt: "Big Gains", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/aoZIB0CD_400x400-removebg-preview-4Gd4ZXnDsQ68LmnX8q0qQYiaZhPEq8.png", alt: "Smiling Man", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/k7fIGGig_400x400-hlYSOEl9OyNYnsBTo4mu5gHm3QAs00.jpg", alt: "Sniper" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/soc6w-Ns_400x400-removebg-preview-euOeR0SJWQC8OR8rjmfFqLROtdlyWl.png", alt: "Man with Straw Hat", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/3BGNdpW7_400x400-LiwO9RnLCP5KTY1TOvvPsTwAntj5ly.jpg", alt: "Frog Character" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file-v9mfl41rVIjiInpuRyldxE6aLHL3c8.png", alt: "Man with Beard", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/file%20(1)-S3y4yN5KXeyVZbxMmXalRSd8WGOZ1d.png", alt: "Smiling Man in White Shirt", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/_w8lM6Sd_400x400-removebg-preview-o5eZstNGqHuwOKXpcKs6O9zt0tIOmC.png", alt: "Woman with Long Hair", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/sq_uLO3c_400x400-removebg-preview-RXURhZFDlrV0d4lAHEh6TB39QwbRLY.png", alt: "Man with Blue Lighting", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/bSLOihgP_400x400-MgGXNNBYIiiWogryXW7knUaxZBQjEI.jpg", alt: "Lethality Logo" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/Adobe%20Express%202024-10-19%2012.31.30-wbr4b0cDtGPhhKwWIIZmQcoC0QOqGT.png", alt: "Man in Black Shirt", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/k8ZB5sjB_400x400-jbBi1bcW9tUxKQi0GlrC2boSMf6ws7.jpg", alt: "Bull Market Logo" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/0qYDxmB0_400x400-VEpKVgSmYbHu7KzsoN994lozzb1ts7.png", alt: "Smiling Asian Woman", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/TraderNick-XFBB0M7HtDApAui3GxXCueVT8h04Z8.png", alt: "TraderNick", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/channels4_profile%20(1)-4dauEgVAKknt2BEGY890lufJyH7Anf.png", alt: "Man in Green Hoodie", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/yHCwrONO_400x400-3CG2N4tbAulRwGjokde1OTf7zkAaF3.png", alt: "Zeussy", className: "bg-white" },
  { src: "https://hebbkx1anhila5yf.public.blob.vercel-storage.com/AMTrades_profile-cxazzDMdefc6ENK916ajtkIug7anUo.png", alt: "AM Trades", className: "bg-white object-cover object-[center_top]" },
]